apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName  }}
spec:
  type: {{  .Values.serviceType  }}
  selector:
    project: {{ .Values.projectName  }}
    app: {{ .Values.appName  }}
  ports:
    - port: {{  .Value.appPort  }}
      targetPort: {{  .Values.appPort  }}