#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: {{ .Values.appName  }}
#data:
#  {{ .Values.configMapData | toYaml | indent 2 }}
#
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ .Values.appName }}
data:
  {{ .Values.configMapData | toYaml | indent 2 }}

