#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ .Values.appName  }}
#spec:
#  type: {{  .Values.serviceType  }}
#  selector:
#    project: {{ .Values.projectName  }}
#    app: {{ .Values.appName  }}
#  ports:
#    - port: {{  .Values.appPort  }}
#      targetPort: {{  .Values.appPort  }}


apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    project: roboshop
    app: catalogue
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    project: roboshop
    app: user
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    project: roboshop
    app: cart
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    project: roboshop
    app: shipping
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    project: roboshop
    app: payment
  ports:
    - port: 8080
      targetPort: 8080